SistemaVotacionAutomatizada/Controllers/CandidatosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaVotacionAutomatizada.Models;

namespace SistemaVotacionAutomatizada.Controllers
{
    public class CandidatosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CandidatosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Candidatos
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Candidatos.Include(c => c.Partido).Include(c => c.PuestoElectivos);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Candidatos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var candidatos = await _context.Candidatos
                .Include(c => c.Partido)
                .Include(c => c.PuestoElectivos)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (candidatos == null)
            {
                return NotFound();
            }

            return View(candidatos);
        }

        // GET: Candidatos/Create
        public IActionResult Create()
        {
            ViewData["PartidoId"] = new SelectList(_context.Partidos, "Id", "Nombre");
            ViewData["PuestoElectivosId"] = new SelectList(_context.PuestoElectivos, "Id", "Nombre");
            return View();
        }

        // POST: Candidatos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,Email,Photo,Estado,PartidoId,PuestoElectivosId")] Candidatos candidatos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(candidatos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PartidoId"] = new SelectList(_context.Partidos, "Id", "Nombre", candidatos.PartidoId);
            ViewData["PuestoElectivosId"] = new SelectList(_context.PuestoElectivos, "Id", "Nombre", candidatos.PuestoElectivosId);
            return View(candidatos);
        }

        // GET: Candidatos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var candidatos = await _context.Candidatos.FindAsync(id);
            if (candidatos == null)
            {
                return NotFound();
            }
            ViewData["PartidoId"] = new SelectList(_context.Partidos, "Id", "Nombre", candidatos.PartidoId);
            ViewData["PuestoElectivosId"] = new SelectList(_context.PuestoElectivos, "Id", "Nombre", candidatos.PuestoElectivosId);
            return View(candidatos);
        }

        // POST: Candidatos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellido,Email,Photo,Estado,PartidoId,PuestoElectivosId")] Candidatos candidatos)
        {
            if (id != candidatos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(candidatos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CandidatosExists(candidatos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PartidoId"] = new SelectList(_context.Partidos, "Id", "Nombre", candidatos.PartidoId);
            ViewData["PuestoElectivosId"] = new SelectList(_context.PuestoElectivos, "Id", "Nombre", candidatos.PuestoElectivosId);
            return View(candidatos);
        }

        // GET: Candidatos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var candidatos = await _context.Candidatos
                .Include(c => c.Partido)
                .Include(c => c.PuestoElectivos)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (candidatos == null)
            {
                return NotFound();
            }

            return View(candidatos);
        }

        // POST: Candidatos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var candidatos = await _context.Candidatos.FindAsync(id);
            _context.Candidatos.Remove(candidatos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CandidatosExists(int id)
        {
            return _context.Candidatos.Any(e => e.Id == id);
        }
    }
}

SistemaVotacionAutomatizada/Controllers/CiudadanosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaVotacionAutomatizada.Models;

namespace SistemaVotacionAutomatizada.Controllers
{
    public class CiudadanosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CiudadanosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Ciudadanos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Ciudadanos.ToListAsync());
        }

        // GET: Ciudadanos/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ciudadanos = await _context.Ciudadanos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ciudadanos == null)
            {
                return NotFound();
            }

            return View(ciudadanos);
        }

        // GET: Ciudadanos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ciudadanos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,Email,Estado")] Ciudadanos ciudadanos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ciudadanos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ciudadanos);
        }

        // GET: Ciudadanos/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ciudadanos = await _context.Ciudadanos.FindAsync(id);
            if (ciudadanos == null)
            {
                return NotFound();
            }
            return View(ciudadanos);
        }

        // POST: Ciudadanos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Nombre,Apellido,Email,Estado")] Ciudadanos ciudadanos)
        {
            if (id != ciudadanos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ciudadanos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CiudadanosExists(ciudadanos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ciudadanos);
        }

        // GET: Ciudadanos/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ciudadanos = await _context.Ciudadanos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ciudadanos == null)
            {
                return NotFound();
            }

            return View(ciudadanos);
        }

        // POST: Ciudadanos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var ciudadanos = await _context.Ciudadanos.FindAsync(id);
            _context.Ciudadanos.Remove(ciudadanos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CiudadanosExists(string id)
        {
            return _context.Ciudadanos.Any(e => e.Id == id);
        }
    }
}

SistemaVotacionAutomatizada/Controllers/PartidosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaVotacionAutomatizada.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.FileProviders;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using SistemaVotacionAutomatizada.DTO;

namespace SistemaVotacionAutomatizada.Controllers
{
    [Authorize]
    public class PartidosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment hostingEnvironment;
        private readonly IMapper _mapper;


        public PartidosController(ApplicationDbContext context, IMapper mapper, IHostingEnvironment hostingEnvironment)
        {
            this.hostingEnvironment = hostingEnvironment;
            this._mapper = mapper;
            _context = context;
        }

        // GET: Partidos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Partidos.ToListAsync());
        }

        // GET: Partidos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var partidos = await _context.Partidos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (partidos == null)
            {
                return NotFound();
            }

            return View(partidos);
        }

        // GET: Partidos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Partidos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PartidosDTO model)
        {
            var partido = new Partidos();
            if (ModelState.IsValid)
            {

                string uniqueName = null;
                if (model.Logo != null)
                {
                    var folderPath = Path.Combine(hostingEnvironment.WebRootPath, "images");
                    uniqueName = Guid.NewGuid().ToString() + "_" + model.Logo.FileName;
                    var filePath = Path.Combine(folderPath, uniqueName);

                    if (filePath != null) model.Logo.CopyTo(new FileStream(filePath, mode: FileMode.Create));
                }


                partido = _mapper.Map<Partidos>(model);

                partido.Logo = uniqueName;

                _context.Add(partido);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Partidos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var partido = await _context.Partidos.FindAsync(id);
            if (partido == null)
            {
                return NotFound();
            }
            var partidoDto = _mapper.Map<PartidosDTO>(partido);
            return View(partidoDto);
        }

        // POST: Partidos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, PartidosDTO dto)
        {
            if (id != dto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var partido = await _context.Partidos.FirstOrDefaultAsync(d => d.Id == dto.Id);

                    string uniqueName = null;
                    if (dto.Logo != null)
                    {
                        var folderPath = Path.Combine(hostingEnvironment.WebRootPath, "images");
                        uniqueName = Guid.NewGuid().ToString() + "_" + dto.Logo.FileName;
                        var filePath = Path.Combine(folderPath, uniqueName);

                       
                        if (!string.IsNullOrEmpty(partido.Logo))
                        { 
                            var filePathDelete = Path.Combine(folderPath, partido.Logo);

                            if (System.IO.File.Exists(filePathDelete))
                            {
                                var fileInfo = new System.IO.FileInfo(filePathDelete);
                                fileInfo.Delete();
                            }
                        }

                        if (filePath != null) dto.Logo.CopyTo(new FileStream(filePath, mode: FileMode.Create));
                    }


                    partido.Nombre = dto.Nombre;
                    partido.Descripcion = dto.Descripcion;
                    partido.Estado = dto.Estado;
                    
                    partido.Logo = uniqueName;

                    _context.Update(partido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PartidosExists(dto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dto);
        }

        // GET: Partidos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var partidos = await _context.Partidos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (partidos == null)
            {
                return NotFound();
            }

            return View(partidos);
        }

        // POST: Partidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var partidos = await _context.Partidos.FindAsync(id);
            _context.Partidos.Remove(partidos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PartidosExists(int id)
        {
            return _context.Partidos.Any(e => e.Id == id);
        }
    }
}

SistemaVotacionAutomatizada/Views/Home/MenuAdmin.cshtml
<h1>Menú Administrador</h1>

<head>
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
</head>

<div class="card-deck">
    <div class="col mb-4">
        <div class="card h-100">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRj7c05VnN6Jhy4ftISKsql3RUJWVCDtyRBtPZ9URk3u5z8QSJ0"
                 class="card-img-top" alt="Ciudadanos Image">
            <div class="card-body">
                <h5 class="card-title">Ciudadanos</h5>
                <p class="card-text">Crear y editar ciudadanos del padrón electoral</p>
            </div>
            <div class="card-body">
                <a href="@Url.Action("Index","Ciudadanos")" class="btn btn-primary">Acceder</a>
            </div>
        </div>
    </div>

    <div class="col mb-4">
        <div class="card h-100">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR7b0XTsjRYCIzYSSQCaC9RmZWv-QMM5AcTqkayALwWc7GcRqze"
                 class="card-img-top" alt="Candidatos Image">
            <div class="card-body">
                <h5 class="card-title">Candidatos</h5>
                <p class="card-text">Seleccionar los ciudadanos que optan por puestos políticos</p>
            </div>
            <div class="card-body">
                <a href="@Url.Action("Index","Candidatos")" class="btn btn-primary">Acceder</a>
            </div>
        </div>
    </div>

    <div class="col mb-4">
        <div class="card h-100">
            <img src="https://www.netclipart.com/pp/m/17-179524_political-clipart-voting-ballot-elections-icon.png"
                 class="card-img-top" alt="Elecciones Image">
            <div class="card-body">
                <h5 class="card-title">Elecciones</h5>
                <p class="card-text">Administrar los procesos electorales del país</p>
            </div>
            <div class="card-body">
                <a href="@Url.Action("Index","Elecciones")" class="btn btn-primary">Acceder</a>
            </div>
        </div>
    </div>
</div>

<div class="card-deck">
    <div class="col mb-4">
        <div class="card h-100">
            <img src="https://cdn4.iconfinder.com/data/icons/election-world-flat/64/senate-congress-government-senator-political-512.png"
                 class="card-img-top" alt="Puestos Image">
            <div class="card-body">
                <h5 class="card-title">Puestos Electivos</h5>
                <p class="card-text">Crear y editar los puestos electivos disponibles del estado</p>
            </div>
            <div class="card-body">
                <a href="@Url.Action("Index","PuestoElectivos")" class="btn btn-primary">Acceder</a>
            </div>
        </div>
    </div>

    <div class="col mb-4">
        <div class="card h-100">
            <img src="https://cdn4.iconfinder.com/data/icons/baseball-18/64/29_versus_team_emblem_baseball_player_match_sport-512.png"
                 class="card-img-top" alt="Partidos Image">
            <div class="card-body">
                <h5 class="card-title">Partidos Políticos</h5>
                <p class="card-text">Administrar los partidos políticos aprobados por la Junta Central Electoral</p>
            </div>
            <div class="card-body">
                <a href="@Url.Action("Index","Partidos")" class="btn btn-primary">Acceder</a>
            </div>
        </div>
    </div>

    <div class="col mb-4">
        <div class="card h-100">
            <img src="https://cdn4.iconfinder.com/data/icons/united-states-presidential-election/97/usa-us-united-states-america-american-election-politics-elections_51-512.png"
                 class="card-img-top" alt="Resultados Image">
            <div class="card-body">
                <h5 class="card-title">Resultados Elecciones</h5>
                <p class="card-text">Visualización de los resultados de las elecciones ejecutadas</p>
            </div>
            <div class="card-body">
                <a href="@Url.Action("Index","VotosElecciones")" class="btn btn-primary">Acceder</a>
            </div>
        </div>
    </div>
</div>

SistemaVotacionAutomatizada/Views/Home/ValidadorCedula.cshtml
@model SistemaVotacionAutomatizada.ViewModels.CiudadanosViewModel

<h1>Validador de Cédulas</h1>

<form class="form-inline">
    <div class="form-group mx-sm-3 mb-2">
        <label for="Cedula" class="sr-only">Cédula</label>
        <input type="text" class="form-control" id="Cedula" placeholder="Ingresar Cédula">
        <span asp-validation-for="Id"></span>
    </div>
    <button type="submit" class="btn btn-primary mb-2">Validar</button>
</form>